:time_estimate: 5

= Lab: Configure Edge Devices

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Configure managed devices by using inline configuration in their device specifications.

WARNING: Work in progress

== Before you begin

You need a customer portal account with access to a Red Hat Enterprise Linux (RHEL) subscription.
It could be a https://developers.redhat.com/products/rhel/download[Red Hat Developer program] free subscription.

You need a _development machine_ running RHEL, which contains two test VMs already enrolled into your RHEM server by a xref:ch3-enroll:s2-enroll-lab.adoc[previous lab].

You also need a _server machine_ running RHEL, to which you also have unrestricted sudo access, which was already configured with RHEM.

Finally, you need a _private registry_ to store bootc container images for your managed edge devices.

If you are using the course classroom, your _development machine_ is the `workstation` VM.
Log in as the user `student` with password `student`.

== Instructions

////

Configure devices so they can access a private OCI container registry, and switch the OS image to one which includes an embedded application.

* Build a new bootc container image which contains an application, such as a web server, and minimal required settings, such as enabling it in systemd and firewalld.

* No need to build an update or installation media, because the update will be performed by RHEM directly from a container registry.

* The previous lab, provisioning devices from ISO (a disconnected workflow), or from QCOW2, left devices without secrets to access the private container registry.

* Try to switch those devices to a different image and notice it fails.

* Add the registry TLS certificate and credentials as inline device configurations, and now they successfully update to the new image.

* The previous bullet requires an afterupdate hook to run the update-ca-trust command

* Access the device and verify the application works as intended.

* Prove other devices were left untouched.

* Change a file which is managed by RHEM and verify that RHEM reverts the change, to demonstrate it works as a “kubernetes-style” reconciliation loop and prevents configuration drift

* Update another different device (to the same image and settings) to demonstrate it done from both the CLI and web UI?

////

At the end of the previous lab, you had two managed devices which were provisioned from the same installation disk.
Right now, they have identical settings, among them a well-known SSH key, which is considered insecure because it's available to any field personel with possess an installation media.
You will remediate this by configuring your managed devices with different SSH keys, provided as inline configurations in each device manifest.

Then you will exercise RHEM's ability to detect and correct configuration drift, by making manual changes to configuration files, and observing that RHEM restores the configurations set for each device.

1. Verify that you have the outcomes of previous labs.
If you do not, go back and complete them, because you need their outcomes to continue with this course.

.. There is a clone of the course samples repository on your home directory.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
LICENSE  README.md  antora.yml  enroll  modules  webapp
--

.. There are two local test VMs, named `edge-1` and `edge-2`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
-------------------------
 -    edge-1   shut off
 -    edge-2   shut off
--

.. If your test VMs are not started, because you stopped your classroom environment since completing the previous lab, start them now.
+
[source,subs="verbatim,quotes"]
--
$ *virsh start edge-1*
Domain 'edge-1' started
$ *virsh start edge-2*
Domain 'edge-2' started
--

.. Enter the `test-enroll` directory, which contains the Containerfile, kickstart script, and SSH key used to provision the two test VMs.
+
[source,subs="verbatim,quotes"]
--
$ *cd temp-enroll*
$ *ls*
Containerfile  bib-iso.sh  config.toml  config.yaml  edge-key  edge-key.pub  output  rhem-enroll.iso  virt-install.sh
--

.. Log in on RHEM, as an administrator, and verify that there are two managed devices, which correspond to the two test VMs.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl login -u admin -p redhat https://servera.lab.example.com:3443*
Login successful.
$ *flightctl get device -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  alias=edge-1,rhel=9.6,type=noapps
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  <none>  Unknown Unknown         Unknown         rhel=9.6,type=noapps,alias=edge-2
--

.. Wait a few moments and repeat the latest command until both managed devices return as `OnLine` and `UpToDate`.

2. Configure the second test VM using the RHEM web UI.

.. Open a web browser and visit `\https://servera.lab.example.com`

.. Log in as the `student` user with the `student` password.
Notice we are NOT using the `admin` user, because you do NOT require full administrator privileges on RHEM to manage devices.
+
GRAB SCREENSHOT

.. On the left panel, click *Devices* and click the icon with three vertical icons in the row of the `edge-2` device. 
Then click *Edit device configurations*.
NOTE: The same option is available from the *Actions* button in the device details page.
+
GRAB SCREENSHOT

.. On the *General info* tab of the *Edit device* page, click *Next*.
+
GRAB SCREENSHOT

.. On the *Device template* tab, click *Add configuration* and fill the form as follows:
+
--
...  *Source name*: `ssh-key`

... *Source type*: `Inline configuration`
--
+
GRAB SCREENSHOT

.. When you select the source type, the page expands to show the *File 1* heading with a couple additional fields.
Leave the form as it is, do not click anywhere else, because we have to generate the content for the ssk-key file.

.. Now switch from the web browser to a terminal, but do NOT close your web browser, and run the following command to create a new SSH key pair which is exclusive to the second device.
+
[source,subs="verbatim,quotes"]
--
$ *ssh-keygen -N '' -f edge-2-key -C 'key for the edge-2 managed device'*
Generating public/private rsa key pair.
...
--

.. Display the public key file and copy its contents to the clipboard, so you can paste it on your web browser.
Of course, your SSH key will have different contents than the ones listed here.
+
[source,subs="verbatim,quotes"]
--
$ *cat edge-2-key.pub*
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILy6lU52yOY7IZ2BFpQhCQaQNBvyo1ydbsd5uyzPZBNq key for the edge-2 managed device
--

.. When you select the source type, the page expands to show the *File 1* heading with a couple additional fields.
Fill them as follows:
+
--
...  *File path on the device*: `/home/core/.ssh/authorized_keys`

... *Content*: <paste here the contents of your SSH key public file>
--
+
NOTE: Instead of doing cut-and-paste from the terminal to the web browser, you could use the *Browse* button to select the `~/temp/enroll/edge-2-key.pub` file in the *Content* field.
+
GRAB SCREENSHOT

.. Scroll down, not changing any of the other fields from *File 1*, and click *Add configuration* again.
+
You could add multiple files to the same configuration, but when the files are not directly related to each other, it improves readability and maintainability of the configuration having files as distinct inline configuration items.

.. fill the fields inside *Configuration 2* as follows:
+
--
...  *Source name*: `motd`

... *Source type*: `Inline configuration`
--
+
GRAB SCREENSHOT


.. And fill the fields from the new *File 1* panel as follows:
+
--
...  *File path on the device*: `/etc/motd`

... *Content*: `Under new management!`
--
+
GRAB SCREENSHOT

.. Do not make any change to applications nor services, and click *Next*

.. On the *Updates* tab, leave *Use basic configurations* checked, and click *Next*

.. On the *Review and save* tab, verify that two configurations are listed, named `hostname` and `motd`, and click *Save*.

3. Verify that the managed device synchronizes with RHEM and receives the new configurations.

.. After clicking *Save*, you are in the details page for the `edge-2` device.
Its *System status* panel should display an *Update status* of `Out-of-date`.
+
GRAB SCREENSHOT

.. Wait until the *Update status* changes to `Up-to-date` and switch to a terminal window.
+
GRAB SCREENSHOT

.. Open a SSH session using the new key.
+
Notice that, if you reuse a previous `ssh` command from your history, you would use the old key and it would ask for the password for the `core` user.
Also notice the message from `/etc/motd`.
+
[source,subs="verbatim,quotes"]
--
$ *ssh -i edge-2-key -p 8222 core@127.0.0.1*
Under new management!
Last login: Thu Dec 18 20:03:46 2025 from 172.25.250.254
[core@enroll ~]$ 
--

.. Logs from the RHEM agent would indicate there was a reconciliation of the device configuration.
+
[source,subs="verbatim,quotes"]
--
$ *sudo journalctl -u flightctl-agent | tail -n 2*
Dec 18 20:02:52 enroll flightctl-agent[820]: time="2025-12-18T20:02:52.191095Z" level=info msg="Version updated from '13' to '14'"
Dec 18 20:03:22 enroll flightctl-agent[820]: time="2025-12-18T20:03:22.434238Z" level=info msg="Spec reconciliation complete: current version 14"
--

4. Change a configuration file and verify that RHEM will undo your edits.

.. If you didn't notice on your lastest SSH log in, there is "a message of day".
+
[source,subs="verbatim,quotes"]
--
$ *cat /etc/motd*
Under new management!
--

.. Change it to something else.
+
[source,subs="verbatim,quotes"]
--
$ *sudo bash -c "echo 'Sysadmin doing nasty things' > /etc/motd"*
$ *cat /etc/motd*
Sysadmin doing nasty things
--

.. Also change the system time zone.
+
[source,subs="verbatim,quotes"]
--
$ *timedatectl show -p Timezone*
Timezone=UTC
$ *sudo timedatectl set-timezone "Europe/Rome"*
$ timedatectl show -p Timezone
Timezone=Europe/Rome
--

.. Wait a few moments and verify that the message reverts to the one set by RHEM.
+
[source,subs="verbatim,quotes"]
--
$ *cat /etc/motd*
Under new management!
--

.. Notice that the time zone change will NOT revert, because RHEM is not managing the file `/etc/localtime`, so you must revert that change manually.
+
[source,subs="verbatim,quotes"]
--
$ timedatectl show -p Timezone
Timezone=Europe/Rome
$ *sudo timedatectl set-timezone UTC*
--

5. Apply similar configurations to the `edge-1` managed device, but this time using the CLI.

.. Copy and inspect the template manifest from the course samples repository.
+
If you compare it with the complete YAML manifest form devices, which you already saw in the previous lab, you will notice the absense of some metadata fields and of all status fields.
Manifests which you apply should focus on the device specification, and provide just the device UUID and labels on its metadata.
+
[source,subs="verbatim,quotes"]
--
$ *cp ../rhde-rhem-samples/config/edge-1.yaml .*
$ *less edge-1.yaml*
include::1@samples:config:example$edge-1.yaml[]
--

.. Generate an SSH key for the device.
+
[source,subs="verbatim,quotes"]
--
$ *ssh-keygen -N '' -f edge-1-key -C 'key for the edge-1 managed device'*
Generating public/private rsa key pair.
...
--

.. Insert the correct UUID for the device in the manifest
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=$( flightctl get device -o name -l alias=edge-1 )*
$ *echo $UUID*
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
$ *sed -i "s|REPLACE_WITH_UUID|$UUID|" edge-1.yaml*
--

.. Insert the new SSH key in the manifest.
+
[source,subs="verbatim,quotes"]
--
$ *SSH_PUB_KEY=$( cat edge-1-key.pub )*
$ *sed -i "s|REPLACE_WITH_SSH_KEY|$SSH_PUB_KEY|" edge-1.yaml*
--

.. Review the `edge-1.yaml` manifest file and verify that it contains no more `REPLACE_WITH` markers.

.. Apply the manigest on RHEM.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl apply -f edge-1.yaml*
edge-1.yaml: applying device/{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}: 200 OK
--

.. Wait until the device synchonizes with RHEM.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device $UUID -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  OutOfDate        NoApplications  alias=edge-1,rhel=9.6,type=noapp
...
$ *flightctl get device $UUID -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  alias=edge-1,rhel=9.6,type=noapp
--

.. Verify that the device actually contains the new configurations, by starting an SSH session using the newly generated key.
+
Also remember that, in the previous lab, you created the file `/root/device.txt` only in the `edge-1` test VM.
+
[source,subs="verbatim,quotes"]
--
$ *ssh -i edge-1-key -p 8122 core@127.0.0.1*
Under new management!
[core@enroll ~]$ *sudo ls /root*
anaconda-ks.cfg  buildinfo  device.txt  original-ks.cfg
[core@enroll ~]$ *exit*
--

//77. If, by any reason, an agent fails to apply a configuration update, it will NOT retry. 
//You must apply another configuration change to the RHEM server so the agent fetches a new rendered config to apply.

////

The agent has insufficient permissions (on its SELinux policy) to set the hostname.
https://issues.redhat.com/browse/EDM-2833

I could workaround with 'setenforce 0' and wait for an update... but maybe I should have a "plan B" to not depend on it.

Create feature requests in the RHEM project (EDM?) -- recover the conversation, I tried it long ago and it failed because of improper configuration in JIRA. Anyway, I'd have other requests, such as:

- explain command
- whoamI command (to get a token)
- cp command (derived from console + redirection, see the sos report blob)
https://github.com/flightctl/flightctl/blob/724dfaeef04cbc4b891864908b1398fce2b0bc3c/docs/user/using/troubleshooting.md#generating-and-downloading-an-sos-report

////

== What's next

In the next activity, you will update devices with a new RHEL release, by updating their bootc container image.