:time_estimate: 5

= Lab: Update Edge Devices

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Update the operating system image on managed devices.

WARNING: Not started yet

== Before you begin

You need a customer portal account with access to a Red Hat Enterprise Linux (RHEL) subscription.
It could be a https://developers.redhat.com/products/rhel/download[Red Hat Developer program] free subscription.

You need a _development machine_ running RHEL, which contains two test VMs already enrolled into your RHEM server by a xref:ch3-enroll:s2-enroll-lab.adoc[previous lab].

You also need a _server machine_ running RHEL, to which you also have unrestricted sudo access, which was already configured with RHEM.

Finally, you need a _private registry_ to store bootc container images for your managed edge devices.

Your _development machine_ requires internet access to download RPM packages and container images.

If you are using the course classroom, your _development machine_ is the `workstation` VM.
Log in as the user `student` with password `student`.

== Instructions

////

Split from a single lab which was configure AND update.

Configure devices so they can access a private OCI container registry, and switch the OS image to one which includes an embedded application.

* Build a new bootc container image which contains an application, such as a web server, and minimal required settings, such as enabling it in systemd and firewalld.

* No need to build an update or installation media, because the update will be performed by RHEM directly from a container registry.

* The previous lab, provisioning devices from ISO (a disconnected workflow), or from QCOW2, left devices without secrets to access the private container registry.

* Try to switch those devices to a different image and notice it fails.

* Add the registry TLS certificate and credentials as inline device configurations, and now they successfully update to the new image.

* The previous bullet requires an afterupdate hook to run the update-ca-trust command

* Access the device and verify the application works as intended.

* Prove other devices were left untouched.

* (tentative) Change a file which is managed by RHEM and verify that RHEM reverts the change, to demonstrate it works as a “kubernetes-style” reconciliation loop and prevents configuration drift

* Update another different device (to the same image and settings) to demonstrate it done from both the CLI and web UI?

////

You will also configure your managed devices with secrets required to access a private OCI container registry, so they can fetch bootc container images, and update them to use a different image than the one used during enrollment.
The new bootc container image contains an embedded web application.

1. Verify that you have the outcomes of previous labs.
If you do not, go back and complete them, because you need their outcomes to continue with this course.

.. There is a clone of the course samples repository on your home directory.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
LICENSE  README.md  antora.yml  enroll  modules  webapp
--

.. There are two local test VMs, named `edge-1` and `edge-2`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
-------------------------
 -    edge-1   shut off
 -    edge-2   shut off
--

.. If your test VMs are not started, because you stopped your classroom environment since completing the previous lab, start them now.
+
[source,subs="verbatim,quotes"]
--
$ *virsh start edge-1*
Domain 'edge-1' started
$ *virsh start edge-2*
Domain 'edge-2' started
--

.. Log in on RHEM, as a non-administrator, and verify that there are two managed devices, which correspond to the two test VMs.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl login -u admin -p redhat https://servera.lab.example.com:3443*
Login successful.
$ *flightctl get device -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  rhel=9.6,type=noapps,alias=edge-2
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  <none>  Unknown Unknown         Unknown         rhel=9.6,type=noapps,alias=edge-2
--

.. Wait a few moments and repeat the latest command until both managed devices return as `OnLine` and `UpToDate`.

2. Build and publish a bootc container image which contains a web application.

.. Copy the Containerfile and related files for the web application image to a work directory.
Then make the work directory your current directory.
+
[source,subs="verbatim,quotes"]
--
$ *cp -r rhde-rhem-samples/webapp temp-webapp*
$ *cd temp-webapp*
--

.. Review the Containerfile that builds a bootc image whith contains an embedded web applicaion.
+
It is similar to the enrollment image, from a previous lab, adding the Apache HTTP Server and firewall services.
+
[source,subs="verbatim,quotes"]
--
$ *less Containerfile*
include::1@samples:webapp:example$Containerfile[]
--
+
NOTE: If you want to try with the current lastest release of the upstream project, edit your Containerfile to remove the version component `-1.0.0~rc` from the package `flightctl-agent`.

.. Your _development machine_ should be already registere with the Red Hat subscription manager, from a previous lab, but you may have to log in again on the Red Hat registry.
+
[source,subs="verbatim,quotes"]
--
$ *sudo subscription-manager status*
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Registered
$ *podman login registry.redhat.io*
Login Succeeded!
--

.. Build the bootc container image.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *podman build -t rhem-webapp .*
STEP 1/2: FROM registry.redhat.io/rhel9/rhel-bootc:9.6
...
Successfully tagged localhost/rhem-webapp:latest
{rhem-webapp-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
--

.. Publish the container image in the private registry.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo copy containers-storage:localhost/rhem-webapp:latest docker://registry.lab.example.com:5000/rhem-webapp:v1.0*
...
Writing manifest to image destination
--
+
////
ERROR 500 on push to private registry. Its disk is full :-(
I was able to enable deletion on the registry delete some folders, and run garbage collections, freeing up a couple GB.
It seems I need a larger utility VM!
https://stackoverflow.com/questions/25436742/how-to-delete-images-from-a-private-docker-registry

Open shell on utility, sudo -i
[root@utility /root]# systemctl stop registry
[root@utility /root]# cd /opt/registry
[root@utility registry]# rm -rf data/docker/registry/v2/repositories/openshift4/
[root@utility registry]# rm -rf data/docker/registry/v2/repositories/rhel10/
[root@utility registry]# systemctl start registry
[root@utility registry]# podman exec -it registry sh
/ # registry garbage-collect -m /etc/distribution/config.yml
...
/ # exit
////

.. There is no need to create an installation disk from that image, because RHEM will handle switching managed devices to it.

3. Update the second test VM to use the new image, by using the web interface.
+
IMPORTANT: The first attempt is expected to fail, but we will troubleshoot the issue and fix it.

.. Open a web browser and visit `\https://servera.lab.example.com`

.. Log in as the `student` user with the `student` password.
+
GRAB SCREENSHOT

.. On the left pane, select the menu:Devices page, and click the link corresponding to the `edge-2` managed device, to enter its details page.
+
GRAB SCREENSHOT

.. On the top right, select menu:Actions[Edit device configurations] to enter the *Edit device* page.
+
GRAB SCREENSHOT

.. Click menu:Next or select the menu:"Device Template" tab and type `registry.lab.example.com:5000/rhem-webapp:v1.0` on the *System image* field.
+
GRAB SCREENSHOT

.. Click menu:Next until you reach the menu:"Review and save" tab, and click menu:Save.

.. The managed device details page should show an `Out-of-date` *Update status* in the *System status* panel, and if you click the warning icon next to *System image (running)*, it will indicate there's a mismatch.
+
GRAB SCREENSHOT

.. After a few moments, or if you refresh your web browser, the *Update status* will change to `Updating`, meaning it is attempting to download and switch to the new booc container image.
+
GRAB SCREENSHOT

.. After a few more momentos, the *Update status* will change back to `Out-of-date` and, if you click the status, you will see an error message which includes the text: `before update: prefetch: pulling oci target registry.lab.example.com:5000/rhem-webapp:v1.0: pull image: code: 125: Trying to pull registry.lab.example.com:5000/rhem-webapp:v1.0`
+
GRAB SCREENSHOT

.. The private registry requires authentication credentails, but these were not provided by its bootc image nor kickstart during provisioning.
We will solve the issue by providing those credentials using RHEM.

.. ALSO NEED THE CA CERTIFICATE. TOO MUCH TO DO USING THE GUI???

5. Configure the managed device with credentials to download bootc container images from the private registry.

.. Switch to a terminal, but do NOT close your web browser.

.. Create a containers authentication file, and access the new bootc container image using this file.
Then copy the contents of the file to the clipboard.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *podman login --authfile auth.json -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo inspect --authfile auth.json --format '{{ json .RepoTags }}' docker://registry.lab.example.com:5000/rhem-webapp:v1.0*
["v1.0"]
$ *cat auth.json *
{
        "auths": {
                "registry.lab.example.com:5000": {
                        "auth": "c3R1ZGVudDpyZWRoYXQ="
                }
        }
}
--
+
//sudo cp /run/containers/0/auth.json /etc/ostree/auth.json
+
//NOTE: In a production setup, both the private registry and RHEM would be configured with a TLS certificate signed by a corporate CA and you would need only to add that CA to all your servers and workstations, including your edge devices.

.. GUESS I NEED TO USE THE CLI BECAUSE I NEED A HOOK TO RUN 'update-ca-trust'... FAIL ANOTHER SELINUX ISSUE, cannot update /etc/pki -- will work around by adding it to the image, but then I miss the opportunity to showcase hooks. :-(

.. Now adding the CA of the registry to the image, so I still add the auth with RHEM.

.. Back to your web browser, enter the manged device details page for the `edge-2` device end edit its device configurations.

.. Click menu:"Add configuration" and fill in the fields as follows:
+
--
... *Source name*: `registry-auth`

... *Source type*: `Inline configuration`

... *File path on device*: `/etc/ostree/auth.json`

... *Content*: either paste the contents of your `auth.json` file or use the menu:Browse button to open it.
--

.. Click menu:Next until you reach the menu:"Review and save" tab and click menu:Save.

.. After a few moments, you should see the device status change to `Updating` and, if everything is fine, to `???`.
+
NOTE: You can observe the update status of the device from the *Devices* page, if you wish.

.. TBD

5. Update the first test VM to use the new image, by using the CLI.

.. TBD

== What's next

In the next activity, you will decomission devices so they are not managed by RHEM anymore.