:time_estimate: 5

= Lab: Update Edge Devices

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Update the operating system image on managed devices.

== Before you begin

You need a customer portal account with access to a Red Hat Enterprise Linux (RHEL) subscription.
It could be a https://developers.redhat.com/products/rhel/download[Red Hat Developer program] free subscription.

You need a _development machine_ running RHEL, which contains two test VMs already enrolled into your Edge Manager server by a xref:ch3-enroll:s2-enroll-lab.adoc[previous lab].

You also need a _server machine_ running RHEL, to which you also have unrestricted sudo access, which was already configured with Edge Manager.

Finally, you need a _private registry_ to store bootc container images for your managed edge devices.

Your _development machine_ requires internet access to download RPM packages and container images.

If you are using the course classroom, your _development machine_ is the `workstation` VM.
Log in as the user `student` with password `student`.

== Instructions

You will configure your managed devices with secrets required to access a private OCI container registry, so they can fetch bootc container images, and update them to use a different image than the one used during enrollment.
The new bootc container image contains an embedded web application, which you will access to verify that the update completed successfully.

1. Verify that you have the outcomes of previous labs.
If you do not, go back and complete them, because you need their outcomes to proceed with this lab.

.. There is a clone of the course samples repository on your home directory.
+
[source,subs="verbatim,quotes"]
--
$ *cd*
$ *ls rhde-rhem-samples*
LICENSE  README.md  antora.yml  enroll  modules  webapp
--

.. There are two local test VMs, named `edge-1` and `edge-2`.
+
[source,subs="verbatim,quotes"]
--
$ *virsh list --all*
 Id   Name     State
-------------------------
 -    edge-1   shut off
 -    edge-2   shut off
--

.. If your test VMs are not running, because you stopped your classroom environment since completing the previous lab, start them now.
+
[source,subs="verbatim,quotes"]
--
$ *virsh start edge-1*
Domain 'edge-1' started
$ *virsh start edge-2*
Domain 'edge-2' started
--

.. Verify that your _development machine_ is registered to Red Hat, so it can access package repositories of any RHEL version.
+
[source,subs="verbatim,quotes"]
--
$ *sudo subscription-manager status*
+-------------------------------------------+
   System Status Details
+-------------------------------------------+
Overall Status: Registered
--

.. Verify that you can access RHEL containers.
You may get a different hash for the RHEL base bootc container image because `9.6` is a floating tag.
+
[source,subs="verbatim,quotes"]
--
$ *podman login registry.redhat.io*
...
Login Succeeded!
$ *skopeo inspect --format '{{.Digest}}' docker://registry.redhat.io/rhel9/rhel-bootc:9.6*
sha256:d64013d886f00ff8afd3141918139d6a6789612d7ce4d3b5c4ffc3b98fc9dec1
--

.. Verify that you have access to a private container registry.
+
[source,subs="verbatim,quotes"]
--
$ *podman login -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *podman search registry.lab.example.com:5000/ubi9*
NAME                                     DESCRIPTION
registry.lab.example.com:5000/ubi9/ubi
--
+
NOTE: Later in this lab, you will login again on both the Red Hat registry and your private registry as the root user, because different Linux users do not share container registry authentication tokens.

.. Log in to Edge Manager, as an operator, and verify that there are two managed devices, which correspond to the two test VMs.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl login -u student -p student https://servera.lab.example.com:3443*
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
$ *flightctl get device -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  rhel=9.6,type=noapps,alias=edge-1
{edge-2-uuid-bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb}    edge-2  <none>  Unknown Unknown         Unknown         rhel=9.6,type=noapps,alias=edge-2
--

.. Wait a few moments and repeat the latest command until both managed devices return as `OnLine` and `UpToDate`.

2. Build and publish a bootc container image, which contains a web application.

.. Copy the Containerfile and related files for the web application image to a work directory.
Then make the work directory your current directory.
+
[source,subs="verbatim,quotes"]
--
$ *cp -r rhde-rhem-samples/webapp temp-webapp*
$ *cd temp-webapp*
--

.. Review the Containerfile for an embedded web application.
+
It is similar to the enrollment image, from a previous lab, adding the Apache HTTP Server and firewall services.
+
[source,subs="verbatim,quotes"]
--
$ *less Containerfile*
include::1@samples:webapp:example$Containerfile[]
--
+
NOTE: If you want to try this with the current latest release of the upstream project, edit your Containerfile to remove the version component `-1.0.0` from the package `flightctl-agent`.
+
IMPORTANT: The previous Containerfile relies on a custom configuration for the Systemd tempfiles service, which ensures the Apache HTTP Server finds work directories it needs in the `/var` and `/run` directories.
These directories are set up by its RPM packages, and such a setup only works at first provisioning, failing at `bootc update` and `bootc switch`.
Using the Systemd tempfiles services is a common workaround for such scenarios.

.. Copy the public certificate of the private container registry.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *cp ../temp-enroll/domain.crt .*
--

.. Build the bootc container image.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *podman build -t rhem-webapp .*
STEP 1/2: FROM registry.redhat.io/rhel9/rhel-bootc:9.6
...
Successfully tagged localhost/rhem-webapp:latest
{rhem-webapp-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
--

.. Publish the container image in the private registry.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *skopeo copy containers-storage:localhost/rhem-webapp:latest docker://registry.lab.example.com:5000/rhem-webapp:v1.0*
...
Writing manifest to image destination
--
+
////
ERROR 500 on push to private registry. Its disk is full :-(
I was able to enable deletion on the registry delete some folders, and run garbage collections, freeing up a couple GB.
It seems I need a larger utility VM!
https://stackoverflow.com/questions/25436742/how-to-delete-images-from-a-private-docker-registry

Open shell on utility, sudo -i
[root@utility /root]# systemctl stop registry
[root@utility /root]# cd /opt/registry
[root@utility registry]# rm -rf data/docker/registry/v2/repositories/openshift4/
[root@utility registry]# rm -rf data/docker/registry/v2/repositories/rhel10/
[root@utility registry]# systemctl start registry
[root@utility registry]# podman exec -it registry sh
/ # registry garbage-collect -m /etc/distribution/config.yml
...
/ # exit
////

.. There is no need to create an installation disk from that image, because Edge Manager will handle switching managed devices to it.

3. Update your second test VM to use the new image, by using the web interface.
+
IMPORTANT: The first attempt at updating your test VM is expected to fail, but you will troubleshoot for the root cause of the issue and fix it.

.. Open a web browser and visit `\https://servera.lab.example.com`

.. Log in as the `student` user with the `student` password.

.. On the left pane, select the menu:Devices[] page, and click the link corresponding to the `edge-2` managed device, to enter its details page.

.. On the top right, select menu:Actions[Edit device configurations] to enter the *Edit device* page.

.. Click menu:Next[] or select the menu:Device Template[] tab and type `registry.lab.example.com:5000/rhem-webapp:v1.0` on the *System image* field.

.. Click menu:Next[] until you reach the menu:Review and save[] tab, and click menu:Save[].

.. The managed device details page should show an *Update status* of `Out-of-date` in the *System status* panel, and if you click the warning icon next to *System image (running)*, it will indicate there's a mismatch.

.. After a few moments, the *Update status* will change to `Updating`, meaning it is attempting to download and switch to the new bootc container image.
+
You can click the `Updating` status to see a longer message describing what updates are pending, in this case, pending download of the bootc container image.

.. After a few moments, the *Update status* will change back to `Out-of-date` and, if you click the status, you will see an error message that indicates a failure to download the bootc container image.

.. The private registry requires authentication credentails, but these were not provided by its bootc image nor by kickstart during provisioning.
You will solve the issue by providing those credentials using Edge Manager.
+
//.. ALSO NEED THE CA CERTIFICATE. TOO MUCH TO DO USING THE GUI??? No, because of SELinux issues, it must be in the bootc image.

4. Configure the managed device with credentials to download bootc container images from the private registry.

.. Switch to a terminal, but do NOT close your web browser.

.. Create a containers authentication file, and access the new bootc container image using this file.
Then copy the contents of the file to the clipboard.
+
[source,subs="verbatim,quotes"]
--
$ *podman login --authfile auth.json -u student -p redhat registry.lab.example.com:5000*
Login Succeeded!
$ *skopeo inspect --authfile auth.json --format '{{ json .RepoTags }}' docker://registry.lab.example.com:5000/rhem-webapp:v1.0*
["v1.0"]
$ *cat auth.json*
{
        "auths": {
                "registry.lab.example.com:5000": {
                        "auth": "c3R1ZGVudDpyZWRoYXQ="
                }
        }
}
--
+
//sudo cp /run/containers/0/auth.json /etc/ostree/auth.json
+
//NOTE: In a production setup, both the private registry and Edge Manager would be configured with a TLS certificate signed by a corporate CA and you would need only to add that CA to all your servers and workstations, including your edge devices.

.. Back to your web browser, enter the managed device details page for the `edge-2` device and edit its device configurations.

.. Scroll down until you see the link menu:Add configuration[] and click it.
Fill in the fields as follows:
+
--
... *Source name*: `registry-auth`

... *Source type*: `Inline configuration`

... *File path on device*: `/etc/ostree/auth.json`

... *Content*: either paste the contents of your `auth.json` file or use the menu:Browse[] button to open it.
--

.. Click menu:Next[] until you reach the menu:Review and save[] tab and click menu:Save[].

.. Right after you save device configuration changes, the device displays an `Out-of-date` with the error message from before the latest changes.
After a few moments, the device status changes to `Updating` and it start downloading the new bootc container image.
+
If you click the `Updating` status again, you may see the pop-up message changing to indicate that the device is applying the new configuration, which is a sign that the device finished downloading its new bootc container image.
+
If everything is fine, after a few moments, the device update status will change to `Up-to-date`.
+
NOTE: You can also monitor the update status of the device from the *Devices* page, if you prefer.

5. Verify that the device is running the new system image.

.. Enter the device details page for the `edge-2` device, if you are not already there, and click the menu:Terminal[] tab.
+
Run the `bootc status` command, to show that the webapp bootc container is the currently booted system image, and the enrollment bootc container is now the rollback image.
+
You can also verify that the `httpd` service is active and use the `curl` command to see its default web page.
+
////
[core@enroll ~]$ sudo journalctl -u httpd | tail
...
Need to add tmpfiles config to the webapp image so it works as an update image.
Dec 20 01:59:41 enroll systemd[1]: Starting The Apache HTTP Server...
Dec 20 01:59:41 enroll httpd[881]: (2)No such file or directory: AH02291: Cannot access directory '/etc/httpd/logs/' for main error log
Dec 20 01:59:41 enroll httpd[881]: AH00014: Configuration check failed
Dec 20 01:59:41 enroll systemd[1]: httpd.service: Main process exited, code=exited, status=1/FAILURE
Dec 20 01:59:41 enroll systemd[1]: httpd.service: Failed with result 'exit-code'.
Dec 20 01:59:41 enroll systemd[1]: Failed to start The Apache HTTP Server.

It is looking more complicated than my php scenario from rhde-bootc-update :-(
httpd is split into multiple packages, with many scriptlets and many /var files in each package

This is the list of files I need to provide, considering all pachages (that are dependencies of httpd)
/var/www -- def content, not using
/var/www/cgi-bin -- def content, not using
/var/www/html -- def content, not using
/run/httpd
/run/httpd/htcacheclean -- no need
/var/cache/httpd -- do I reallyu need this?
/var/cache/httpd/proxy -- not using proxy
/var/lib/httpd -- what's here?
/var/log/httpd

I may also need to provide sysusers. No, the apache user and group are there. Because they have fixed id, that is, they're NOT dynamic users?

It works after adding just /run/httpd /var/log/httpd to tmpfiles.d
////

.. You can access the mock web application from your _development machine_, by using the port redirection that was set up at VM creation time:
+
[source,subs="verbatim,quotes"]
--
$ *curl 127.0.0.1:8208*
This would be the HTML and JavaScript code of a single-page web application.
--

6. Update your first test VM to use the new image, by using the CLI.

.. Now you will apply the same operating system and configuration update, but using YAML manifests.
Start by reviewing the `edge-1-webapp.yaml` file, which is in the same folder as the Containerfile for the new bootc image.
+
There should be nothing new to you in this manifest: it includes the updated SSH key and message of day files from the previous lab, and adds the private registry credentials and the reference to the new bootc container image, just like you did for the `edge-2` device.
+
Feel free to make edits to the `edge-1.yaml` file yourself, instead of starting from the `edge-1-webapp.yaml` file.
+
[source,subs="verbatim,quotes"]
--
$ *less edge-1-webapp.yaml*
include::1@samples:webapp:example$edge-1-webapp.yaml[]
--

.. Insert the correct UUID for the device in the manifest
+
[source,subs="verbatim,quotes,attributes"]
--
$ *UUID=$( flightctl get device -o name -l alias=edge-1 )*
$ *sed -i "s|REPLACE_WITH_UUID|$UUID|" edge-1-webapp.yaml*
--

.. Insert the device-specific SSH key in the manifest.
+
[source,subs="verbatim,quotes"]
--
$ *SSH_PUB_KEY=$( cat ../temp-enroll/edge-1-key.pub )*
$ *sed -i "s|REPLACE_WITH_SSH_KEY|$SSH_PUB_KEY|" edge-1-webapp.yaml*
--

.. Insert the container tools authentication file in the manifest.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *REGISTRY_AUTH=$( jq -c . auth.json )*
$ *sed -i "s|REPLACE_WITH_AUTH_JSON|$REGISTRY_AUTH|" edge-1-webapp.yaml*
--

.. Review the `edge-1-webapp.yaml` manifest file and verify that it contains no more `REPLACE_WITH` markers.

.. Apply the manifest on Edge Manager.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl apply -f edge-1-webapp.yaml*
edge-1-webapp.yaml: applying device/{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}: 200 OK
--

.. Wait until the device synchronizes with Edge Manager.
+
If you wish, you can request the YAML output of the `flightctl get device`, by appending `-o yaml`, to see detailed status information as the device is updated.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl get device $UUID -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  OutOfDate        NoApplications  alias=edge-1,rhel=9.6,type=noapps
...
$ *flightctl get device $UUID -o wide*
NAME                                                    ALIAS   OWNER   SYSTEM  UPDATED         APPLICATIONS    LABELS
{edge-1-uuid-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}    edge-1  <none>  Online  UpToDate        NoApplications  alias=edge-1,rhel=9.6,type=noapps
--

7. Verify that your first test VM is running with updates applied.

.. Verify the currently booted system image.
+
[source,subs="verbatim,quotes,attributes"]
--
$ *flightctl console device $UUID -- bootc status*
● Booted image: containers-storage:registry.lab.example.com:5000/rhem-webapp:v1.2
        Digest: sha256:{rhem-webapp-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
       Version: 9.6 (2025-12-02 08:30:48 UTC)

  Rollback image: registry.lab.example.com:5000/rhem-enroll:v1.0
          Digest: sha256:{rhem-enroll-v1-shaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
         Version: 9.6 (2025-12-02 08:30:48 UTC)
--

.. Verify that the Apache HTTP Server is active.
+
[source,subs="verbatim,quotes"]
--
$ *flightctl console device $UUID -- systemctl is-active httpd*
active
--

.. Use the port redirection that you configured at VM creation time to verify that it is serving the mock web application.
+
[source,subs="verbatim,quotes"]
--
$ *curl 127.0.0.1:8108*
This would be the HTML and JavaScript code of a single-page web application.
--

In this lab, you performed operating system updates on two managed devices, by using the Edge Manager web interface and its CLI. 
You also demonstrated that the fact that a device can be provisioned from a bootc container image does not ensure that it is configured to fetch bootc container updates from private registries. Finally you showed that Edge Manager is able to provide such configurations at the same time it updates the system image of managed devices.

== What's next

In the next activity, you will decommission devices so they are not managed by Edge Manager anymore.