:time_estimate: 5

= Managing Edge Device with Red Hat Edge Manager

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Describe what is RHDE, its high level architecture, and relations to other infrastructure management tools from Red Hat, such as Red Hat Satellite, Red Hat Ansible Automation Platform (AAP), and Red Hat Advanced Cluster Management (ACM).


WARNING: Work in progress

////

Describe what is RHDE, its architecture, and relations to other infrastructure management tools from Red Hat, such as Red Hat Satellite, Red Hat Ansible Automation Platform (AAP), and Red Hat Advanced Cluster Management (ACM).

* Focus on the role of each tool and the actual requirements of RHEM and RHDE: an authentication provider, DNF package repositories, and a container image registry.

* Mention edge servers (RHEL) and edge gateways/devices (RHDE) as existing in a typical edge site and that RHEM can manage both. It is not tied to RHDE only.

* This course does not address the specifics of managing RHDE devices running MicroShift.

* Provide simple examples of tasks you could perform with either RHEM or ACM, or with either RHEM or RHDE, from this blog post.
https://www.redhat.com/en/blog/managing-red-hat-device-edge-tools-and-strategies

* High-level architecture of RHEM, not detailing its components.

* Why an agent-based approach (pull) is best suited to the challenges of edge devices and edge sites, compared to a centralized (push) approach.

* RHEM requires managed devices to run image mode for RHEL (bootc).

* RHEM is inspired by Kubernetes, sharing many of the same design patterns, and enables a similar style of GitOps for the operating system. But RHEM does not require Kubernetes to run. It can run on Kubernetes, if you like, and also manage Kubernetes (MicroShift), if you want.

* Do we need a quick introduction/refresher about RHDE?

////

== Introduction do Edge Computing

_Edge computing_ is any computing infrastructure that located close to the source of data generation or production, such as a plant floor, a retail store, or an offshore oil rig.

An _edge site_ is any location where you have edge computing resources.
It could be as small as a single automated teller machine in a retail store, a couple point of sale systems in a drug store, or an automated pick up location, such as an Amazon Locker, in a train terminal. 

Some edge sites, like a cruise ship or a department store, may contain a large number of computing resources and even a "server room" with compute and network racks, uninterruptive power supplies, and other resources similar to a data center.
But other edge sites may put compute resources in an environment which the ower of the edge resources do not control, vulnerable to the climate and tampering by outsiders.

Unlike traditional centralized and regional data centers, and large office buildings and campuses, edge sites often face limitations regarding power, cooling, and hardware capabilities.
Edge sites may also be disconnected, air-gapped, or have low bandwidth connections to the outside.

But more important than hardware and networing capabilities, edge sites often lack on-site Information Technology (IT) expertise, prioritizing other needs from the _Operational Technology_ (OT) domain, such as PLC programming, radiology equipment maintenance, or non-IT and non-OT personel such as store management.

Traditional IT management tools focus on the high capacity, always connected, and highly standardized world of data centers and cater to the needs of IT personel.
Edge management tools, on the other hand, must be friendlier to OT personal and deal with the large variety of form factors, intermitent network connectivity, and limited capabilities, of edge sites.

While edge computing used to be the domain of highly specialized and proprietary devices and software, there's a desire to be closer to the world of edge computing, to enable workload portability, better integration with corporate systems, and migrating to the edge novell applications such as artificial intelligence.

Nowadays, there's an emerging class of edge devices which are much closer to traditional computers, having the capability to run Red Hat Enterprise Linux and benefit from containerized applications, and leading vendors are applying more and more of the open source tools and processes that used to be viable only for cloud computing also to edge computing.

== Introduction to Red Hat Device Edge

_Red Hat Device Edge_ (RHDE) is a solution for edge computing, which is comprised of thee products and technologies from Red Hat:

Red Hat Enterprise Linnux (RHEL)::
An operating system foundation, optimzed for edge computing (in addition to cloud and data center), that ensures stability and reliability.

Red Hat build of MicroShift::
A lightweight Kubernetes distribution, based on Red Hat OpenShift, but optimized for resource-constrained environments.

Red Hat Edge Manager (RHEM)::
A control plane that streamlines fleet management of edge devices.

Most of components of RHDE, except for MicroShift are available as part of other Red Hat products, and when that happens they are not changed compared to what is provided by Red Hat Device Edge.

For example, the RHEL you get from RHDE is the same RHEL you get from other products which include it.
There are no changes in RHEL capabilities.
It is the same Linux kernel, the same libraries, and the same system services.
This ensures that, as developers build and test applications on the data center, that software runs unchanged on edge devices running RHDE, as long as their applications do not demand more capabilities than available on the targer devices and sites.

The main benefit of purchasing RHDE instead of other Red Hat products which provie these components is the cost.
Most RHEL subscriptions assume data center servers, which many CPUs, lots of memory, which can serve hundreds or even thousand of users.

RHDE, on the other hand, has a cost which is compatible with small devices, which are single-CPU, have a small amount of memory, and usually run a single application for a single user at a time.
Nothing prevents RHDE from running multiple applications in parallel, serving some dozen users, and this is common in a class of edge devices usually known as _edge gateways_, which collect data and control multiple smaller edge devices, like security cameras and industrial sensors, which would not be able to run RHDE by themselves.

== Introduction to Red Hat Edge Manager

The best way of describing Red Hat Edge Manager is as _Kubernetes-style GitOps for the operating system_.
RHEM manages declarative state about managed devices and continuouly monitor that state, reconcilliating any deviations.
If an administrator alters the declared state, RHEM ensures that managed devices are changed to be consistent with the new state.

You can store the declarative configuration of managed devices inside of RHEM's own database, but the recommended practice is to store it in a git repository, which makes updates and testing easier.

Red Hat Edge Manager controls three aspects of device configurations:

. The operating system image running on devices, as a bootc container image (image mode for RHEL).

. Operating system and application configuration files in `/etc` and `/var`.

. Containerized applications running on devices, from single containers to Podman Quadlets managed by the System Daemon (Systemd).

Red Hat Edge Manager is based on the https://github.com/flightctl/flightctl[Flight Control] open source project, and its capabilities are expanding quickly.
Future releases of RHEM may support managing devices not running image mode for RHEL and additional types of applications, such as Helm applications.

The way RHEM supports image mode for RHEL and containerized applications adapts to differnet ways IT and OT teams organize themselves.
Some teams may opt for a fully "appliance" approach, where applications are embeded into the operating system image as a single artifact, and OT field people just turns the device on.
Other teams may opt for a right separation of concern, where an infrastructure team manages operating system configurations and hardware lifecycle, while business other teams manage application lifecycle and data.

The concept of _fleet management_ is key to RHEM.
This concepts applies a proven cloud-based practice to operating system management: managing applications and cloud instances as undifferentiated sets, instead of unique instances each one with their specific settings.
If you heard the analogy of _pets vs cattle_, RHEM enables you to manage the operating system and applications in edge devices as _cattle_.

For example, you define once the configuration of all pont of sale (PoS) systems in all your stores, and let RHEM apply the configuration to all of them.
RHEM will also let you know which ones were updated or not to the latest configuration.
Or you could define a configuration only for the PoS systems in a singel store or all stores in a single a region, before applying it to all your remaining stores.

== Red Hat Edge Manager standalone and with other management tools from Red Hat

RHEM may be used by itself, as the all-purpose device management tool, from provisioning to decomissioning, and to manage all applications running on managed devices.

Or it can work integrated with other management tools from Red Hat, such as Red Hat Ansible Automation Platform (AAP) and Red Hat Advanced Cluster Management (ACM).
Teams that have mature practices and skills on such tools may benefit from using them together with RHEM, and over time adopt more and more of RHEM capabilities which they perceive as more reliable or easier to use than the capabilities they are alreaydy familiar with and were already using for data centers and clouds.

If you opt for deploying RHEM integrated with either ACM or AAP, RHEL looks like it is part of those platforms, using the same authentication and permission mechanisms, but still offering its own features and APIs.
For example, if you deploy RHEM on OpenShift, with or without ACM, RHEM still stores managed device state on its own database instead of using kubernetes custom resources to store managed device state.

Even if you opt for deploying RHEM standalone on either RHEL or OpenShift, you may still need other tools to provide capabilities not included in RHEM, for example:

* *Red Hat Satellite*, to manage RPM package repositories made available to developers who build operating system images.

* *Red Hat Quay*, to manage operating system images (bootc container images), application container images, helm charts, Large Language Models (LLMs), and other software artifacts made available to developers and edge sites.

* *Red Hat Ansible Automation Platform* to manage networking gear in edge sites or between those sites and corporate data centers.

* *Red Hat OpenShift Container Platform* to offer developers an application platform to build, test, and secure containerized applications that will be deployed on edge sites.

* *Red Hat AI* to fine-tune standard LLMs, populate Retrieval-Aumented Generation (RAG) databases, test guard-rails to ensure model safety, evaluate models to avoid bias, and develop AI-enabled application that will be deployed on edge sites.

And you could opt to use tools for a number of vendors, other than Red Hat, to provide similar capabilities.

In this course, we focus on the simplest deployment modes of RHEM standalone in RHEL, without other Red Hat tools, and using open source web servers and container registries to provide the minimum required infrastructure, so we can focus on operating RHEM and managing edge devices with RHEM.

== Red Hat Edge Manager: Inspired by Kubernetes

RHEM is inspired by Kubernetes, but it does not requires Kubernetes at all.
IT and OT professionals who are already familiar with Kubernetes may notice many similarities between the structore of their APIs, their CLIs, and their underlying concepts, sich as the reconcilliation loop.

But RHEM is still a new product, and you may miss some of the conforts already provided by Kubernetes.
We expect most of them will be added over time.
For example, RHEM does not provide a self-description of its own API resources, like Kubernetes offers with its `explain` command.
And RHEM is not extensible with custom resource types.

On the other hand, RHEM offers a much less intimimating learning curve, with a feature set tailored to the specific needs of edge device management.
Kubernetes is considered difficult to master because it offers features for diverse IT needs, which are common in data center and cloud computing scenarios, from software development to virtual machine management.
But you do not need all those features to manage edge devices and edge sites.

RHEM does not attempt to be the single tool to manage all your edge computing needs.
For example, it is not designed to manage network geat at edge sites -- for that you may use Red Hat Ansible Automation Platform.
RHEM is designed to manage edge devices running RHEL, with or withour MicroShift at scale and under the constraints of connectivity that common at edge sites, enabling workflows that are friendly to OT personel.

== What's Next

The first activity of this course checks that you have all you need to perform the labs, such as access to RHEL packages and container images.
