:time_estimate: 5

= Lab: Install Red Hat Edge Manager Standalone

_Estimated reading time: *{time_estimate} minutes*._

Objective::

Deploy RHEM on RHEL with minimal requirements.

WARNING: Work in progress

== Before you begin

You need a customer portal account with access to a Red Hat Enterprise Linux (RHEL) subscription.
It could be a https://developers.redhat.com/products/rhel/download[Red Hat Developer program] free subscription.

You need a _development machine_ running RHEL, to which you have unrestricted sudo access.
//On the next activities, you will use the _development machine_ to run test VMs that stand in for edge devices to be managed by RHEM.

You also need a _server machine_ running RHEL, to which you also have unrestricted sudo access.

Both your _development machine_ and _server machine_ require internet access to download RPM and container images packages.

If you are using the course classroom, your _development machine_ is the `workstation` VM.
Log in as the user `student` with password `student`.
From that machine, you may start SSH sessions to the `servera` VM, which is your _server_ machine, using the same user.
Alternatively, you can open a shell or a console directly on the `servera` VM.

== Instructions

////

* Verify availability of all required packages and container images.

* Install RHEM using dnf

* Configure DNF to use sssd (if not default) and hostname for the UI.

* Generate and use a TLS certificate using the virtual classroom CA, or add the self-signed certificate to the trust store of the development machine. Avoid disabling TLS validation for CLI and web access.

* Check the health of all RHEM systemd services/quadlets/containers.

* Connect to RHEM using CLI and Web interface to assess it is healthy and running.

////

You will install and configure RHEM on your _server machine_, and then you will use your _development machine_ to run the web UI and the CLI of RHEM to verify that your new RHEM instance is up and running.

NOTE: The instructions here use the community artifacts from the flightctl projects, but are expected to work with the product artifacts from RHEM, when they become available, by just switching from the community repository to the RHEM product repository.

1. Install the RHEM services on your _server machine_.

.. Make sure your current shell is on the right machine.
+
[source,subs="verbatim,quotes"]
--
$ *hostname*
servera
--

.. Enable the Flightctl repository from EPEL.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo*
GRAB OUTPUT
--

.. Install the RHEM services.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf install -y flightctl-services*
GRAB OUTPUT
--

.. Edit the RHEM configuration in `/etc/flightctl/service-config.yaml` to use the fully qualified domain (FQDN)
+
[source,subs="verbatim,quotes"]
--
global:
  baseDomain: *servera.lab.example.com*
  auth:
...
--
+
////
.. In my rc1/2 testing, I used the IP address
+
[source,subs="verbatim,quotes"]
--
global:
  baseDomain: *172.25.250.10*
  auth:
...
--

.. I also had to provide an explicit URL, using the IP address, for the OIDC service
+
[source,subs="verbatim,quotes"]
--
...
    pamOidcIssuer:
      enabled: true
      # OIDC issuer URL - must include /api/v1/auth path. Leave empty to auto-configure as https://${global.baseDomain}:8444/api/v1/auth
      issuer: *https://172.25.250.10:8444/api/v1/auth*
      clientId: flightctl-client
...
--
////

.. Start the RHEM services
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl enable --now flightctl.target*
Created symlink '/etc/systemd/system/multi-user.target.wants/flightctl.target' → '/usr/lib/systemd/system/flightctl.target'.
--

.. Verify that the RHEM services are up and running.
+
Be patient, it may take a while until all container images required by RHEM are downloaded from the internet and it initializes its database and cache services.
When it is all done, it is expected that some services will display `exited` as their substatus.
+
[source,subs="verbatim,quotes"]
--
$ *systemctl list-units 'flightctl*' --all*
  UNIT                                 LOAD   ACTIVE SUB     DESCRIPTION                                             
  flightctl-alert-exporter.service     loaded active running Flight Control Alert Exporter service
  flightctl-alertmanager-proxy.service loaded active running Flight Control Alertmanager Proxy service
  flightctl-alertmanager.service       loaded active running Flight Control Alertmanager service
  flightctl-api-init.service           loaded active exited  Flight Control API Initialization
  flightctl-api.service                loaded active running Flight Control API server
  flightctl-certs-init.service         loaded active exited  Flight Control Certificates Initialization
  flightctl-cli-artifacts-init.service loaded active exited  Flight Control CLI Artifacts Certificates Initialization
  flightctl-cli-artifacts.service      loaded active running Flight Control CLI Artifacts service
  flightctl-db-migrate.service         loaded active exited  Flight Control Database Migration service
  flightctl-db-users-init.service      loaded active exited  Flight Control Database Users Initialization
  flightctl-db-wait.service            loaded active exited  Flight Control Database Wait
  flightctl-db.service                 loaded active running PostgreSQL Database for Flightctl
  flightctl-kv.service                 loaded active running Flight Control Key Value service
  flightctl-network.service            loaded active exited  flightctl-network.service
  flightctl-pam-issuer.service         loaded active running Flight Control PAM OIDC Issuer server
  flightctl-periodic.service           loaded active running Flight Control Periodic service
  flightctl-ui-init.service            loaded active exited  Flight Control UI Initialization
  flightctl-ui.service                 loaded active running Flight Control UI
  flightctl-worker.service             loaded active running Flight Control Worker service                           
  flightctl.target                     loaded active active  Flight Control Services Group

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

20 loaded units listed.
To show all installed unit files use 'systemctl list-unit-files'.
--

.. If some of services do not start, you can check their status and log messages, for example:
+
[source,subs="verbatim,quotes"]
--
$ *sudo systemctl status flightctl-api*
[sudo] password for student: 
● flightctl-api.service - Flight Control API server
     Loaded: loaded (/usr/share/containers/systemd/flightctl-api.container; generated)
...
$ *sudo journalctl -u flightctl-api*
Dec 15 13:45:24 servera systemd[1]: Starting flightctl-api.service - Flight Control API server...
Dec 15 13:45:26 servera flightctl-api[2032]: Trying to pull quay.io/flightctl/flightctl-api:1.0.0-rc2...
..
--

.. Verify that the RHEM containers are up and running.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman ps*
CONTAINER ID  IMAGE                                                     COMMAND               CREATED        STATUS        PORTS                                           NAMES
88fee8adbc8a  docker.io/library/redis:7.4.1                             /bin/sh -c redis-...  2 minutes ago  Up 2 minutes  6379/tcp                                        flightctl-kv
dcec17e5ce36  quay.io/sclorg/postgresql-16-c9s:20250214                 run-postgresql        2 minutes ago  Up 2 minutes  5432/tcp                                        flightctl-db
ae375cbd787d  quay.io/prometheus/alertmanager:v0.28.1                   --config.file=/us...  2 minutes ago  Up 2 minutes  9093/tcp                                        flightctl-alertmanager
6735c35b4c94  quay.io/flightctl/flightctl-alert-exporter:1.0.0-rc2      /bin/sh -c ./flig...  2 minutes ago  Up 2 minutes                                                  flightctl-alert-exporter
4adbea0863c4  quay.io/flightctl/flightctl-pam-issuer:1.0.0-rc2          ./flightctl-pam-i...  2 minutes ago  Up 2 minutes  0.0.0.0:8444->8444/tcp                          flightctl-pam-issuer
f7bc10df3b84  quay.io/flightctl/flightctl-worker:1.0.0-rc2              /bin/sh -c ./flig...  2 minutes ago  Up 2 minutes                                                  flightctl-worker
ef129d3b0ba0  quay.io/flightctl/flightctl-alertmanager-proxy:1.0.0-rc2  /bin/sh -c ./flig...  2 minutes ago  Up 2 minutes  0.0.0.0:8443->8443/tcp                          flightctl-alertmanager-proxy
25603c3e2bd3  quay.io/flightctl/flightctl-api:1.0.0-rc2                 /bin/sh -c ./flig...  2 minutes ago  Up 2 minutes  0.0.0.0:3443->3443/tcp, 0.0.0.0:7443->7443/tcp  flightctl-api
b4f26b0f4fa4  quay.io/flightctl/flightctl-ui:1.0.0-rc2                  /bin/sh -c ./flig...  2 minutes ago  Up 2 minutes  0.0.0.0:443->8080/tcp                           flightctl-ui
f204d574cd11  quay.io/flightctl/flightctl-periodic:1.0.0-rc2            /bin/sh -c ./flig...  2 minutes ago  Up 2 minutes                                                  flightctl-periodic
aac92db2a9a6  quay.io/flightctl/flightctl-cli-artifacts:1.0.0-rc2                             2 minutes ago  Up 2 minutes  0.0.0.0:8090->8090/tcp                          flightctl-cli-artifacts
--

.. You can also get logs directly from the containers
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman logs flightctl-api*
time="2025-12-15T13:45:34Z" level=info msg="Starting API service" func=main.main file="/app/cmd/flightctl-api/main.go:40"
..
--

2. For simplicity, configure local users for the RHEM services, on the PAM issuer container.

.. Create groups which correspond to the `admin`, `operator`, and `viewer` roles.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman exec -i flightctl-pam-issuer groupadd flightctl-admin*
$ *sudo podman exec -i flightctl-pam-issuer groupadd flightctl-operator*
$ *sudo podman exec -i flightctl-pam-issuer groupadd flightctl-viewer*
--

.. Create a user named `student` and grant it the `operator` role.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman exec flightctl-pam-issuer adduser student*
$ *sudo podman exec -i flightctl-pam-issuer sh -c 'echo "student:student" | chpasswd'*
$ *sudo podman exec -i flightctl-pam-issuer usermod -aG flightctl-operator student*
--

.. Create a user named `admin` and grant it the `admin` role.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman exec flightctl-pam-issuer adduser admin*
$ *sudo podman exec -i flightctl-pam-issuer sh -c 'echo "admin:redhat" | chpasswd'*
$ *sudo podman exec -i flightctl-pam-issuer usermod -aG flightctl-admin admin*
--

.. Verify you have the requires users and groups on the PAM issuer container.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman exec -i flightctl-pam-issuer groups student*
student : student flightctl-operator
$ *sudo podman exec -i flightctl-pam-issuer groups admin*
admin : admin flightctl-admin
--

.. If you would rather be more throughout verifying users and groups on the PAM issue container.
+
[source,subs="verbatim,quotes"]
--
$ *sudo podman exec -i flightctl-pam-issuer getent passwd student*
student:x:1000:1003::/home/student:/bin/bash
$ *sudo podman exec -i flightctl-pam-issuer getent passwd admin*
admin:x:1001:1004::/home/admin:/bin/bash
$ *sudo podman exec -i flightctl-pam-issuer getent group flightctl-admin*
flightctl-admin:x:1000:admin
$ *sudo podman exec -i flightctl-pam-issuer getent group flightctl-operator*
flightctl-operator:x:1001:student
--

3. Install the RHEM CLI on your _development machine_

.. Make sure your current shell is on the right machine.
+
[source,subs="verbatim,quotes"]
--
$ *hostname*
workstation
--
.. Enable the flight repository from EPEL and install its CLI package.
+
[source,subs="verbatim,quotes"]
--
$ *sudo dnf config-manager --add-repo https://rpm.flightctl.io/flightctl-epel.repo*
GRAB OUTPUT
$ *sudo dnf install -y flightctl-cli*
GRAB OUTPUT
--

.. Verify that the `flightctl` command is in your command PATH.
+
[source,subs="verbatim,quotes"]
--
$ *flightctl version*
Client Version: v1.0.0-rc2
Server Version: Could not read server version
--

.. Copy the self-signed certificate of the RHEM server and add it to the system's trusted CA set.
+
[source,subs="verbatim,quotes"]
--
$ *scp servera:/etc/flightctl/pki/ca-bundle.crt ~*
ca-bundle.crt             100% 1222   128.6KB/s   00:00
$ *sudo cp ca-bundle.crt /etc/pki/ca-trust/source/anchors/*
$ *sudo update-ca-trust extract*
--

.. Log in on the RHEM server.
+
[source,subs="verbatim,quotes"]
--
$ *flightctl login -u admin -p redhat https://servera.lab.example.com:3443*
Login successful.
--
+
////
.. ONCE I CLEAN, WILL IT WARN ABOUT AUTO-SELECTING AN ORG?
+
[source,subs="verbatim,quotes"]
--
$ flightctl login -u admin -p redhat  https://172.25.250.10:3443
Auto-selected organization: 00000000-0000-0000-0000-000000000000 Default
Login successful.
--
////

.. Verify that the CLI can now get the server's version, and that there are no managed devices yet.
+
[source,subs="verbatim,quotes"]
--
$ *flightctl version*
Client Version: v1.0.0-rc2
Server Version: v1.0.0-rc2
$ *flightctl get dev*
NAME    ALIAS   OWNER   SYSTEM  UPDATED APPLICATIONS
--

4. Access the RHEM web UI.

.. Open a web browser and visit `https://servera.lab.example.com`.
You should get a login screen without any web browser warnings about certificate issues.

.. Log in as the `student` user, with password `student`. 
+
If you get a "CSRF error", just try again.

.. You should get the RHEM Overview page, with three gray circles because there are no managed devices to report a status summary.

.. On the left panel, click on *Devices* to verify that there are indeed no managed devices.


== What's next

In the next activity, you will create a bootc container image containing the RHEM client and use it to provision and enroll a test VM which stands in for a managed edge device.